### ISSUE TITLE
It doesn't work for an Atmos bucket in ECS

### ISSUE THREAD

**Issue by sigian80** [EMCECS/bucket-wipe#2]
Hi, 

i try to use bucket-wipe with this data-set:

**-e** http://x.x.x.x:9022 : ECS Community Edition 3.2.x, Atmos service
**-a** ns-bktatmos_user01 : access key used to upload objects in Atmos bucket 
**-s** ********* : the secret key of ns-bktatmos_user01
**0d87e932571b4a908fb16b9fe62eb70c** : Atmos bucket created by this script ( https://community.emc.com/docs/DOC-27822  )

but i always receive this error: 

0          WARN  [Thread-2       ] EcsHostListProvider: **unable to retrieve node list** from x.x.x.x
com.sun.jersey.api.client.UniformInterfaceException: Client response status: 403
        at com.sun.jersey.api.client.WebResource.handle(WebResource.java:688)
        at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
        at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:509)
        at com.emc.rest.smart.ecs.EcsHostListProvider.getDataNodes(EcsHostListProvider.java:150)
        at com.emc.rest.smart.ecs.EcsHostListProvider.getHostList(EcsHostListProvider.java:85)
        at com.emc.rest.smart.PollingDaemon.run(PollingDaemon.java:63)
3          WARN  [Thread-2       ] EcsHostListProvider: could not retrieve node list for VDC x.x.x.x
**Error: Unable to retrieve the secret key for the specified user.
Last key before error: null**
 
The launch command is: java -jar bucket-wipe-1.10.jar -e http://x.x.x.x:9022 -a ns-bktatmos_user01 -s ********* 0d87e932571b4a908fb16b9fe62eb70c 

The namespace on ECS is **ns-bktatmos** that I try to use for -p parameter and I add the option --atmos also but bucket-wipe fails systematically. 

How should I run bucket-wipe correctly? Does it work for this scenario (Atmos bucket in ECS) ?

Looking forward to your reply. 
Thank you in advance

Kind Regards,
SG

**Comment by twincitiesguy** [comment]
@sigian80, please be sure to scrub any public postings of sensitive information, like secret keys or IP addresses.

If you want to use the Atmos protocol (using port 9022 on the node), you must provide the `--atmos` parameter.  If you do that, you should get a different error and post that here.  The error above is because you are trying to use the S3 protocol against the Atmos endpoint, which won't work.

**Comment by twincitiesguy** [comment]
Cleaning up old issues...

FYI, to use bucket-wipe with the Atmos protocol, you will have to build from the [feature-atmos](https://github.com/EMCECS/bucket-wipe/tree/feature-atmos) branch.
